env:
	. venv/Scripts/activate

frun:
	cd ./rentcar/ \
	&& python manage.py runserver

migrate:
	cd ./rentcar/ \
	&& python manage.py makemigrations \
	&& python manage.py migrate

upt-lib:
	pip freeze > requirements.txt