# Generated by Django 3.2.6 on 2022-01-16 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('category', models.CharField(choices=[('Эконом', 'Эконом'), ('Стандарт', 'Стандарт'), ('Бизнес', 'Бизнес'), ('Премиум', 'Премиум'), ('Микроавтобус', 'Микроавтобус'), ('Кроссовер', 'Кроссовер'), ('Внедорожник', 'Внедорожник')], max_length=30, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото автомобиля')),
                ('apacity', models.IntegerField(verbose_name='Вместимость(чел)')),
                ('consumption', models.IntegerField(verbose_name='Расход на 100км')),
                ('transmission', models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика'), ('Гибрид', 'Гибрид')], max_length=10, verbose_name='Тип трансмиссии')),
                ('engine_power', models.IntegerField(verbose_name='Мощность двигателя')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=50, verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateField(verbose_name='Дата сдачии')),
                ('period', models.IntegerField(verbose_name='Период аренды')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('condition', models.ManyToManyField(to='cars.Condition', verbose_name='Условия аренды')),
            ],
            options={
                'verbose_name': 'Сервис аренды',
                'verbose_name_plural': 'Сервис Аренды',
            },
        ),
    ]
