# Generated by Django 3.2.9 on 2022-01-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('Бензиновый', 'Бензиновый'), ('Гибрид', 'Гибрид'), ('Электродвигатель', 'Электродвигатель')], default=1, max_length=40, verbose_name='Тип двигателя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика'), ('Вариатор', 'Вариатор')], max_length=10, verbose_name='Тип трансмиссии'),
        ),
    ]
