# Generated by Django 3.2.9 on 2022-04-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceoptions', '0001_initial'),
        ('cars', '0004_auto_20220406_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_zone',
        ),
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='condition',
            field=models.ManyToManyField(to='serviceoptions.Condition', verbose_name='Условия аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceoptions.delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='insurance',
            field=models.ManyToManyField(to='serviceoptions.Insurance', verbose_name='Тип страхования'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceoptions.extension'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryZone',
        ),
        migrations.DeleteModel(
            name='Extension',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
