# Generated by Django 3.2.9 on 2022-04-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceoptions', '0001_initial'),
        ('cars', '0005_auto_20220407_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceoptions.extension'),
        ),
    ]
