# Generated by Django 3.2.9 on 2022-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_order_order_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active_state',
            field=models.BooleanField(default=True),
        ),
    ]
