# Generated by Django 3.2.9 on 2022-04-17 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_order_active_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='apacity',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='car',
            name='car_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость авто'),
            preserve_default=False,
        ),
    ]
