# Generated by Django 3.2.9 on 2022-05-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_order_active_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active_state',
            field=models.BooleanField(default=True),
        ),
    ]
